import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";
import { ThemeProvider } from "@/components/Theme/ThemeProvider";

const spaceGrotest = Space_Grotesk({
  subsets: ["latin"],
});

export const metadata = {
  title: "Study-Nook | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="light"
      lang="en"
      className={`${spaceGrotest.className} h-full antialiased`}
    >
      <body className="">
        <ThemeProvider>
          <NavBar></NavBar>
          {children}
          <Footer></Footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
