import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";
import { Toaster } from "react-hot-toast";

const spaceGrotest = Space_Grotesk({
  subsets: ["latin"],
});

export const metadata = {
  title: "Study-Nook | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="light"
      lang="en"
      className={`${spaceGrotest.className} h-full antialiased`}
    >
      <body suppressHydrationWarning>
        <NavBar></NavBar>
        {children}
        <Footer></Footer>
        <Toaster
          style={{
            border: "1px solid #D97757",
            padding: "16px",
            color: "#D97757",
          }}
        ></Toaster>
      </body>
    </html>
  );
}
