import { Space_Grotesk } from "next/font/google";
import "./globals.css";

const spaceGrotest = Space_Grotesk({
  subsets: ["latin"],
});

export const metadata = {
  title: "Study-Nook | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="light"
      lang="en"
      className={`${spaceGrotest.className} h-full antialiased`}
    >
      <body className="">{children}</body>
    </html>
  );
}
